export const TOGGLE_LEFT_DRAWER = 'TOGGLE_LEFT_DRAWER';
export const CHANGE_ROUTE = 'CHANGE_ROUTE';
export const FETCH_BUSINESS_RULES_SUCCESS = 'FETCH_BUSINESS_RULES_SUCCESS';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const UPDATE_USER = 'UPDATE_USER';

export const UPDATE_BRANCHES = 'UPDATE_BRANCHES';
export const UPDATE_CURRENT_BRANCH = 'UPDATE_CURRENT_BRANCH';

export const FETCH_FEEDS_SUCCESS = 'FETCH_FEEDS_SUCCESS';
export const FETCH_CONFIGS_SUCCESS = 'FETCH_CONFIGS_SUCCESS';
export const FETCH_FILES_FAILURE = 'FETCH_FILES_FAILURE';

export const CALL_START = 'CALL_START';
export const CALL_SUCCESS = 'CALL_SUCCESS';
export const CALL_FAILURE = 'CALL_FAILURE';

export const LOAD_CONFIG = 'LOAD_CONFIG';
export const RESET_CONFIG = 'RESET_CONFIG';

export const API_FAILED = 'API_FAILED';
export const RESET_API_FAILURE_STATUS = 'RESET_API_FAILURE_STATUS';

export const AUTH_FAILED = 'AUTH_FAILED';
export const RESET_AUTH_FAILURE_STATUS = 'RESET_AUTH_FAILURE_STATUS';

export const UPDATE_FILTER = 'UPDATE_FILTER';
export const ADD_FILTER = 'ADD_FILTER';
