export const TOGGLE_LEFT_DRAWER = 'TOGGLE_LEFT_DRAWER';
export const CHANGE_ROUTE = 'CHANGE_ROUTE';
export const FETCH_BUSINESS_RULES_SUCCESS = 'FETCH_BUSINESS_RULES_SUCCESS';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const UPDATE_BRANCHES = 'UPDATE_BRANCHES';

export const FETCH_FILES_SUCCESS = 'FETCH_FILES_SUCCESS';
export const FETCH_FILES_FAILURE = 'FETCH_FILES_FAILURE';

export const GET_FILE_CONTENTS = "GET_FILE_CONTENTS";
export const UPDATE_FILE_CONTENTS = "UPDATE_FILE_CONTENTS";
